services:
  - type: web
    name: mindcheck-app
    env: node
    plan: free
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000